---
title: "Project 2"
author: "Alessandro Cavalieri"
date: "2026-02-21"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: true
header-includes:
  - \usepackage{dsfont}
  - |
    <script>
      window.MathJax = {
        tex: {
          macros: {
            mathds: ["\\mathbb{#1}", 1]
          }
        }
      };
    </script>
---

$\newcommand{\mathds}[1]{\mathbb{#1}}$

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Problem 1

## Point a

Supposing that the joint density of $U, Z$ up to a normalizing constant is


$$
f^*_{U,Z}(u,z) = \begin{cases}1 & \quad \quad \text{for } 0<u<e^{-z^2/2} \\
0 & \quad \quad \text{elsewhere}
\end{cases} = \mathds{I}_{0<u<e^{-z^2/2}}(u)
$$

We are asked to derive the full conditionals of $U$ and $V$.

1. We start deriving the marginals of $U$ and $V$

**Marginal of $U$**:

$$
\begin{align}
f_U(u) = \int_{-\infty}^{\infty} \mathds{1}_{0<u<e^{-z^2/2}}(u) \ \mathrm dz
\end{align}
$$

# Problem 2

# Problem 3
```{r}
load(url("https://www.math.ntnu.no/emner/TMA4300/2026v/clouds.RData"))     
plot(clouds$z, xlab="Time", ylab="log(Cloud ceiling height)")
```
```{r}
clouds$z
```

```{r}

library(mvtnorm)

mh_sampler <- function(y, n_iter = 10000, burn_in = 1000) {
  n <- length(y)
  p <- 2
  
  # 1. Prepare data for the proposal (*)
  y_curr <- y[2:n]
  X <- cbind(1, y[1:(n-1)])
  Q <- t(X) %*% X
  Q_inv <- solve(Q)
  beta_hat <- Q_inv %*% t(X) %*% y_curr
  ssr <- sum((y_curr - X %*% beta_hat)^2)
  
  # 2. Storage
  samples <- matrix(NA, nrow = n_iter, ncol = 3)
  colnames(samples) <- c("beta0", "beta1", "tau")
  acc_count <- 0
  
  # 3. Log-second function helper
  log_second <- function(b0, b1, tau, y1) {
    if (abs(b1) >= 1) return(-Inf) # Stationary constraint
    val <- 0.5 * log(1 - b1^2) - log(1 - b1) - 
           (tau / 2) * (1 - b1^2) * (y1 - b0 / (1 - b1))^2
    return(val)
  }
  
  # Initial state
  samples[1, ] <- c(beta_hat, 1)
  
  # 4. Metropolis-Hastings Loop
  for (i in 2:n_iter) {
    # Step d: Compositional Sampling from Proposal Q
    tau_prop <- rgamma(1, shape = (n - p) / 2, rate = ssr / 2)
    beta_prop <- rmvnorm(1, mean = beta_hat, sigma = solve(tau_prop * Q))
    
    b0_p <- beta_prop[1]; b1_p <- beta_prop[2]
    b0_c <- samples[i-1, 1]; b1_c <- samples[i-1, 2]; tau_c <- samples[i-1, 3]
    
    # Step c: Compute Log-Acceptance Ratio
    log_alpha <- log_second(b0_p, b1_p, tau_prop, y[1]) - 
                 log_second(b0_c, b1_c, tau_c, y[1])
    
    if (log(runif(1)) < log_alpha) {
      samples[i, ] <- c(b0_p, b1_p, tau_prop)
      acc_count <- acc_count + 1
    } else {
      samples[i, ] <- samples[i-1, ]
    }
  }
  
  cat("Overall Acceptance Rate:", acc_count / (n_iter - 1), "\n")
  return(samples[(burn_in + 1):n_iter, ])
}

res <- mh_sampler(clouds$z)
# Assuming 'res' is the output from mh_sampler(y)
res_mcmc <- as.data.frame(res)

# 1. Trace Plots
par(mfrow=c(3,1), mar=c(4,4,2,1))
plot(res_mcmc$beta0, type="l", col="steelblue", main="Trace Plot: beta0", ylab="Value")
plot(res_mcmc$beta1, type="l", col="darkgreen", main="Trace Plot: beta1", ylab="Value")
plot(res_mcmc$tau, type="l", col="firebrick", main="Trace Plot: tau", ylab="Value")

# 2. Autocorrelation Plots
par(mfrow=c(1,3))
acf(res_mcmc$beta0, main="ACF: beta0")
acf(res_mcmc$beta1, main="ACF: beta1")
acf(res_mcmc$tau, main="ACF: tau")
```


# Problem 4